name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    container: squidfunk/mkdocs-material

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Will try to build the documentation
    - name: Run a multi-line script
      run: |
        mkdocs build
