name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    container: squidfunk/mkdocs-material

    steps:
    - uses: actions/checkout@v1
    - name: Informing the user
      run: echo Will try to build the documentation
    - name: Building the documentation
      run: |
        mkdocs build && find . -name site
    - uses: actions/checkout@master
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      env:
        FTP_SERVER: ${{secrets.FTP_SERVER}}
        FTP_USERNAME: ${{secrets.FTP_USERNAME}}
        FTP_PASSWORD: ${{secrets.FTP_PASSWORD}}
        LOCAL_DIR: /__w/documentation/documentation/site
        #ARGS: --delete        
