name: Deploy Documentation

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    container: squidfunk/mkdocs-material

    steps:
    - uses: actions/checkout@v1
    - name: Building for github
      run: |
        mkdir -p /github/home/.ssh/
        echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
        git remote set-url origin git@github.com:Orange-Pi-Community/documentation.git
        mkdocs gh-deploy
    - name: Building the documentation
      run: |
        mkdocs build 
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      env:
        FTP_SERVER: ${{secrets.FTP_SERVER}}
        FTP_USERNAME: ${{secrets.FTP_USERNAME}}
        FTP_PASSWORD: ${{secrets.FTP_PASSWORD}}
        LOCAL_DIR: site
        #ARGS: --delete        
