name: CI

on: [push]

jobs:
  build:

    runs-on: squidfunk/mkdocs-material

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        sudo apt install -y mkdocs && pip install bdist_wheel mkdocs-material && mkdocs gh-deploy
